create table orders (
    id uuid primary key,
    customer_id varchar(200) not null,
    status varchar(20) not null check (status in ('PENDING', 'CONFIRMED', 'CANCELLED')),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    version bigint not null default 0
);

create index ix_orders_customer_created on orders(customer_id, created_at desc, id);

create table order_items (
    order_id uuid not null references orders(id) on delete cascade,
    sku varchar(200) not null,
    quantity integer not null check (quantity > 0),
    unit_price numeric(19,2) not null check (unit_price >= 0),
    currency varchar(3) not null
);

create table idempotency_records (
    id bigint generated by default as identity primary key,
    principal_id varchar(200) not null,
    request_key varchar(100) not null,
    request_hash varchar(64) not null,
    order_id uuid not null references orders(id),
    created_at timestamptz not null,
    constraint uk_idempotency_principal_key unique(principal_id, request_key)
);

create table outbox_events (
    id uuid primary key,
    aggregate_id uuid not null,
    event_type varchar(100) not null,
    payload text not null,
    occurred_at timestamptz not null,
    published_at timestamptz
);

create index ix_outbox_unpublished on outbox_events(occurred_at) where published_at is null;

create table processed_events (
    id uuid primary key,
    processed_at timestamptz not null
);
